version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kotlin:
      patterns:
      - "org.jetbrains.kotlin:*"
    quarkus:
      patterns:
      - "version.quarkus"
      - "quarkus.platform.version"
      - "io.quarkus*"

- package-ecosystem: gradle
  directory: "/tools/gradle-plugin"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
