:microprofile-open-api: https://github.com/eclipse/microprofile-open-api/

image:https://github.com/smallrye/smallrye-open-api/workflows/SmallRye%20Build/badge.svg?branch=main[link=https://github.com/smallrye/smallrye-open-api/actions?query=workflow%3A%22SmallRye+Build%22]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-open-api&metric=alert_status["Quality Gate Status", link="https://sonarcloud.io/dashboard?id=smallrye_smallrye-open-api"]
image:https://img.shields.io/github/license/thorntail/thorntail.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]

= SmallRye OpenAPI

SmallRye OpenAPI is an implementation of {microprofile-open-api}[Eclipse MicroProfile OpenAPI].

== Instructions

Compile and install this project:

[source,bash]
----
mvn clean install
----

=== Project structure

* link:core[] - The core OpenAPI code, independent of entry point dependencies.
* link:extension-jaxrs[] - The JAX-RS entry point. This module depends on JAX-RS and core.
* link:extension-spring[] - The Spring entry point. This module depends on Spring and core.
* link:extension-vertx[] - The Vert.x entry point. This module depends on Vert.x and core.
* link:implementation[] - Implementation of the Eclipse MicroProfile OpenAPI specification. This just pulls in Core and the JAX-RS extension .
* link:testsuite[] - Test suites.
* link:testsuite/tck[] - Test suite to run the implementation against the Eclipse MicroProfile OpenAPI TCK.
* link:testsuite/extra[] - Extra integration tests not related to the TCK.
* link:tools/maven-plugin[] - Maven plugin that creates the OpenAPI Schema on build.

=== Links

* http://github.com/smallrye/smallrye-open-api/[Project Homepage]
* {microprofile-open-api}[Eclipse MicroProfile OpenAPI]

=== Configuration Extensions
* `mp.openapi.extensions.smallrye.property-naming-strategy` - define a naming strategy to be used globally for all schema properties. Set to one of the following:
** A standard JSON-B naming strategy (listed in `jakarta.json.bind.config.PropertyNamingStrategy`/`javax.json.bind.config.PropertyNamingStrategy`)
** A fully-qualified class name of an implementation of a JSON-B property naming strategy (`jakarta.json.bind.config.PropertyNamingStrategy` or `javax.json.bind.config.PropertyNamingStrategy`)
** A fully-qualified class name of an implementation of a Jackson property naming strategy base class (`com.fasterxml.jackson.databind.PropertyNamingStrategies.NamingBase`). Only the `translate` method is utilized.
* `mp.openapi.extensions.smallrye.maximumStaticFileSize` - Set this value in order to change the maximum threshold for
processed static files, when generating model from them. If not set, it will default to 3 MB.
