name: Publish Gradle Plugin

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: Tag version to perform release
        type: string

jobs:
  publish-tck:
    runs-on: ubuntu-latest
    name: Publish Gradle Plugin
    steps:
      - uses: actions/checkout@v4
        name: checkout ${{inputs.version}}
        with:
          ref: ${{ inputs.version }}

      - uses: actions/setup-java@v4
        name: set up jdk
        with:
          distribution: 'temurin'
          java-version: 17

      - name: build with maven
        run: mvn -B -pl 'tools/gradle-plugin' -am install -DskipTests

      - name: Gradle plugin release ${{ inputs.version }}
        run: |
          mkdir -p ~/.gradle ; echo -e "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}\ngradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" > ~/.gradle/gradle.properties
          cd tools/gradle-plugin && gradle publishPlugins
