name: Publish TCK

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: Tag version to perform release
        type: string

jobs:
  publish-tck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        # Disable older TCK jobs prior to 4.0 GA release
        #- tck-version: "2.0.1"
        #- tck-version: "3.0"
        #- tck-version: "3.1.1"
        - tck-version: "4.0.2"
        - tck-version: "4.1"

    name: MicroProfile OpenAPI TCK ${{ matrix.tck-version }}
    steps:
      - uses: actions/checkout@v5
        name: checkout ${{inputs.version}}
        with:
          ref: ${{ inputs.version }}

      - name: maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-tck-${{ matrix.tck-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: actions/setup-java@v5
        name: set up jdk
        with:
          distribution: 'temurin'
          java-version: 17

      - name: build with maven
        run: mvn -B -pl 'testsuite/tck' -am install -DskipTests

      - uses: actions/setup-java@v5
        name: set up jdk
        with:
          distribution: 'temurin'
          java-version: 11

      - name: execute tck ${{ matrix.tck-version }}
        run: mvn -B test -f testsuite/tck/pom.xml -Dsmallrye.commit=$(git rev-parse HEAD) -Dversion.eclipse.microprofile.openapi=${{ matrix.tck-version }}

      - name: stage tck report
        run: mv testsuite/tck/target/surefire-reports/microprofile-openapi-tck-report.html ./microprofile-openapi-tck-report-${{ matrix.tck-version }}.html

      - name: upload tck report to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ inputs.version }} microprofile-openapi-tck-report-${{ matrix.tck-version }}.html
