name: SmallRye Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}
    env:
      GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}

    steps:
      - uses: radcortez/project-metadata-action@main
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - uses: actions/checkout@v4
        with:
          token: ${{secrets.RELEASE_TOKEN}}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: 'oss.sonatype'
          server-username: 'MAVEN_DEPLOY_USERNAME'
          server-password: 'MAVEN_DEPLOY_TOKEN'
          gpg-private-key: ${{secrets.MAVEN_GPG_PRIVATE_KEY}}
          gpg-passphrase: 'MAVEN_GPG_PASSPHRASE'

      - name: maven release ${{steps.metadata.outputs.current-version}}
        env:
          MAVEN_DEPLOY_USERNAME: ${{secrets.MAVEN_DEPLOY_USERNAME}}
          MAVEN_DEPLOY_TOKEN: ${{secrets.MAVEN_DEPLOY_TOKEN}}
          MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}
        run: |
          java -version
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"
          git checkout -b release
          mvn -B release:prepare -Prelease -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}}
          git checkout ${{github.base_ref}}
          git rebase release
          mvn -B release:perform -Prelease
          git push
          git push --tags

      - name: Gradle plugin release ${{steps.metadata.outputs.current-version}}
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: ./tools/gradle-plugin
          cache-read-only: true
          arguments: publishPlugins -Pgradle.publish.key=${{secrets.GRADLE_PUBLISH_KEY}} -Pgradle.publish.secret=${{secrets.GRADLE_PUBLISH_SECRET}}

      - uses: radcortez/milestone-release-action@main
        name: milestone release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          milestone-title: ${{steps.metadata.outputs.current-version}}

  tck-reporting:
    runs-on: ubuntu-latest
    needs: release

    strategy:
      matrix:
        include:
        - tck-version: "2.0.1"
        - tck-version: "3.0"
        - tck-version: "3.1.2"

    name: MicroProfile OpenAPI TCK ${{ matrix.tck-version }}
    steps:
      - uses: radcortez/project-metadata-action@main
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - uses: actions/checkout@v4
        name: checkout
        with:
          ref: ${{ steps.metadata.outputs.current-version }}

      - name: maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-tck-${{ matrix.tck-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: actions/setup-java@v4
        name: set up jdk
        with:
          distribution: 'temurin'
          java-version: 17

      - name: build with maven
        run: mvn -B -pl '!testsuite/coverage,!testsuite/data,!testsuite/extra,!tools,!tools/gradle-plugin,!tools/maven-plugin,!ui,!ui/open-api-ui,!ui/open-api-ui-forms' install -DskipTests

      - uses: actions/setup-java@v4
        name: set up jdk
        with:
          distribution: 'temurin'
          java-version: 11

      - name: execute tck ${{ matrix.tck-version }}
        run: mvn -B test -f testsuite/tck/pom.xml -Dsmallrye.commit=$(git rev-parse HEAD) -Dversion.eclipse.microprofile.openapi=${{ matrix.tck-version }}

      - name: stage tck report
        run: mv testsuite/tck/target/surefire-reports/microprofile-openapi-tck-report.html ./microprofile-openapi-tck-report-${{ matrix.tck-version }}.html

      - uses: meeDamian/github-release@2.0
        name: upload tck asset to release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.metadata.outputs.current-version }}
          allow_override: true
          gzip: false
          files: microprofile-openapi-tck-report-${{ matrix.tck-version }}.html
